</$objtype/mkfile

# it seems like a bad idea to include '.'
# in the path with executables like 'rm'
# in this directory.
path=/bin

BIN=/$objtype/bin/git
TARG=\
	conf\
	get\
	fs\
	log\
	query\
	repack\
	save\
	send\
	serve\
	walk

RC=\
	add\
	branch\
	clone\
	commit\
	compat\
	diff\
	export\
	hist\
	import\
	init\
	merge\
	pull\
	push\
	rebase\
	revert\
	rm

OFILES=\
	delta.$O\
	objset.$O\
	ols.$O\
	pack.$O\
	proto.$O\
	util.$O\
	ref.$O

HFILES=git.h
DIRS=aux

</sys/src/cmd/mkmany

# Override install target to install rc.
install:V:
	mkdir -p $BIN
	mkdir -p /sys/lib/git
	for (i in $TARG)
		mk $MKFLAGS $i.install
	for (i in $RC)
		mk $MKFLAGS $i.rcinstall

%.rcinstall:V:
	cp $stem $BIN/$stem
	chmod +x $BIN/$stem

all:V:	all.dirs
dirs:V: all.dirs
install:V: install.dirs
installall:V: installall.dirs
clean:V: clean.dirs test.clean
nuke:V: nuke.dirs
test:V: test.dirs

test:V: runtest
runtest:V:
	cd test && mk $MKFLAGS test

test.clean:V:
	cd test && mk $MKFLAGS clean

%.dirs:V:
	for(i in $DIRS) @{
		cd $i
		echo mk $i
		mk $MKFLAGS $stem
	}
